[ids]

*

[main]

# Maps capslock to escape
capslock = esc

# Remaps the escape key to capslock
esc = capslock

numlock = noop	# Disable numlock (gets pressed accidentally)

kp1 = end
kp2 = down
kp3 = pagedown
kp4 = left
kp5 = down
kp6 = right
kp7 = home
kp8 = up
kp9 = pageup

